---
# tasks file for kernel-settings

- name: "Require Correct Linux Distribution"
  assert:
    that: (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_version | version_compare('6.0.0', '>=')) or
          (ansible_distribution == 'Debian'             and ansible_distribution_version | version_compare('7.0.0', '>=')) or
          (ansible_distribution == 'Ubuntu'             and ansible_distribution_version | version_compare('14.0.0', '>='))
    msg:  "This Linux distribution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
  tags: kernel-settings

- name: "Include OS Variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "vars-{{ ansible_distribution }}.yml"
  tags: sudo

- name: "Setting on /proc"
  include: kernel_proc.yml
  tags: kernel-settings

- name: "Setting on /sys"
  include: kernel_sys.yml
  tags: kernel-settings

- name: "Setting on GRUB"
  include: kernel_grub.yml
  tags: kernel-settings
